travis:
  secure:
    BINSTAR_TOKEN: OVF7umn/IlvxBz6nJKBrofJIGr/f+ssIl+Pgj/+iWjvdHcsl4ecUvXy3ih+rXwinlFRCpAKS6O5h4vTFHM3CbcUPGP3uuMM1x9btpA4worXrkkwgvvas1uoX7rPC5UntJXTfmVesnKjlTUDBOn/cfc6+lac1+F2JLKfxalCAG6vkPpvxY5xGDFTn1TpEh1zqnfSOem/vts1m5TvVJd7oIPIQz3Moq3+FUqCi4nviNMt4X3YsiB0UYLIzvXanziujJozyxA7v4fUqqFXfNxQnJvBUwTzaPbRJb3RSBFsLt4H8rLxcY90mVypc/oRAxcVx1Xwg0o7pw0Ipsj/P18c1Mimci16m5EIZqGJJ2habLenZY4Rkq3gcn6lvMGqfus2nUpSzK8NasJ9pN84OuVTMSB7N1n6i7T5ic60vNDxEfUdkPPIDQoPRRRk7vJjJp6C36B+Rn8/eWMtuTTpiB6OIp+u+GtEUKw1otvVphi6agICinHhmi+fexGrCRnT+SIqewBu/OexDNuBS7jUQ0bLpjiUeLhe21mjtJkVC0g1T+rCRZCHcFhk8VOoQN9h8YivVoAKeWOrSY1lAQmwRIFNuse7dcLCyKGBUMlBr0W0Zad9Y5LuEGPvEdTBSct261p9zQ0eP15s0ZDTmAe/NOUalVpI7LBLnm89Upucl9kLmgNM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
