travis:
  secure:
    BINSTAR_TOKEN: c/mcYxHakLBvgm+4xEspvs2p25lpT7/elk6V4Gx/OnbiBSrrHHl3Z+qv41ebSFVTt9j5EA2XR5xoH9mRaopvsQ78Zyz+V7TwD2b93pmfGHFBQ1gJvJ/Zr55PICQhZfkgQdhLBil5K+UU+RFojTjHp2GCp+BnSDrWX0H43lcXEcFK1jZrAM2T5Wd1SGf46jl+0W1yyll5+EKqVxeCysk3c0IP6EAIW50++w9Bs5AVO1o6cg+0p+LOpJmdsqHNH84yz/YATPNS8gAPVv+4TgIM8eAasNWGXIk1qjjAACDiNN2ztaECFw62TdrXtRfvtiF6mAvhcKMujcOUl27AtEPQqZSdW9kkrqJe2pHplIPCIK+fx+6IxSzqVJqima9tShOtjrZA4Gkj9Qc0jILPQtYcio3K/i7zoGVkdS/5eyrHykHz4/g7fnMdGgUZcB1wu5lBP9dLV5aw2eew0Rjj6M7ooQ6VIyvAcgPodPKml2oHJJvR/Bf67fK6V2PAZKcRN7fLlQp91pCsl4ubjJxXfe+ieoJ51vr8+sigMG12fAPv2qctIuUAqh2Ypp+XvoXILnKSWQl87mLIdUb4g4KS6WC4LGG8hNIRloNjSPx8dQKP4y1Z0fAhCO7qY2hx6NrqLBiyobP78veiJ0/WHXMyUs6PwFfFE8QEX0eb6OaOEaLtGU8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
